### ISSUE TITLE
Unusable for Average User

### ISSUE THREAD

**Issue by glow12121** [GitJournal/git-auto-sync#1]
Hi,

Many thanks for designing this script but it seems unusable for an average PC user. I am getting these errors when trying to run the .sh script in the terminal and get git to work. Not to mention the .plist file which I don't even know how to run on my Linux system.

A simple GUI app that would monitor file changes and autosync would be a much needed addition to the GitJournal project, in my view.

```
user@pc ~/ . . . /GitJournal $ bash git-auto-sync.sh 
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

```
user@pc ~/ . . . /GitJournal $ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in / . . . /GitJournal/.git/
```

**Comment by vHanda** [comment]
Hi. Could you please try the latest release? I'll be happy to add more documentation or whatever else you require to get this to work for you.
